# Generated by Django 6.1 on 2026-08-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_slot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='home_slot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
