# Generated by Django 6.1 on 2026-08-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_match_away_slot_match_home_slot_match_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='referee_slot',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
