# Generated by Django 6.1 on 2026-08-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_match_referee_slot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('group_slot', ''), _negated=True), fields=('group_slot',), name='unique_nonempty_team_group_slot'),
        ),
    ]
