# Generated by Django 6.1 on 2026-08-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_team_unique_nonempty_team_group_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, upload_to='team_logos/'),
        ),
    ]
