# Generated by Django 6.1 on 2026-08-26 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('court', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('match', 'Match'), ('opening_ceremony', 'Opening Ceremony'), ('lunch', 'Lunch'), ('closing_ceremony', 'Closing Ceremony'), ('free', 'Free')], max_length=20)),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('day', 'start_time', 'court'),
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='group_slot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='schedule_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='tournament.scheduleevent'),
        ),
    ]
