# Generated by Django 6.1 on 2026-08-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_scheduleevent_alter_team_group_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('match_code', ''), _negated=True), fields=('match_code',), name='unique_nonempty_match_code'),
        ),
    ]
