# Generated by Django 6.1 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_match_code_match_unique_nonempty_match_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='referee_locked',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'Preserve this referee team when automatic assignments '
                    'are recalculated.'
                ),
            ),
        ),
    ]
