# Generated by Django 6.1 on 2026-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_match_participant_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTiebreakResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=30)),
                ('team_set_signature', models.CharField(max_length=255)),
                ('team_order', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'team_set_signature'), name='unique_manual_tiebreak_team_set_per_scope')],
            },
        ),
    ]
